name: hit-marriage
version: ${project.version}
main: es.minehit.marriage.internal.MarriagePlugin
authors:
  - lenis0012
  - biiee3l
softdepend: [Vault, PlotSquared]
api-version: '1.21'
manifest-url: ${updater.manifestUrl}
commands:
  marry:
    description: Comando principak
    usage: /marry <args>
permissions:
  marry.default:
    description: Permite usar los comandos básicos
    default: true